Rakefile
pwshlib.md

Remove the feature/confine pattern from the build of the puppet module; see puppetlabs/puppetlabs-powershell#267

(MAINT) remove feature from puppet module

---

lib/pwsh/util.rb
spec/unit/pwsh/util_spec.rb

This commit adds four new utilities to the gem:
- `snake_case`: returns a string which is `snake_cased`.
- `snake_case_hash_keys`: returns a hash in which all of the keys are `snake_cased`.
- `pascal_case`:  returns a string which is `PascalCased`.
- `pascal_case_hash_keys`:  returns a hash in which all of the keys are `PascalCased`.
- `escape_quotes`: ensures that any string passed will be returned wrapped in double quotes for passing into PowerShell; this is because of the interpolation required when sending code to the PowerShell manager.
- `format_powershell_value`: converts ruby data types into strings of their PowerShell representation for interpolation and passing to the PowerShell manager.
- `custom_powershell_property`: takes a name and an expression and returns a string which …

(FEAT) Add quality of life utilities

---

lib/pwsh/util.rb
spec/unit/pwsh/util_spec.rb

This commit adds a new utility method which will take a hash or an array and recursively turn any discovered hash keys from string keys into symbol keys and return the symbolized hash.

(FEAT) Add method for symbolizing hash keys

---

.rubocop.yml
Gemfile

Prior to this commit rubocop runs in Travis failed on a renamed cop.

(MAINT) Update rubocop config

---

lib/pwsh/util.rb
spec/unit/pwsh/util_spec.rb

Prior to this commit the hash key casing methods, `snake_case_hash_keys` and `pascal_case_hash_keys`, only properly handled hashes, not hashes inside arrays or other objects.
Now, if passed an array, the methods will iterate over each item in the array, recursively casing any keys discovered in hashes. Additionally, they will not error if passed any objects which are not hashes or arrays; instead, they will return that object as-is.

(FEAT) Ensure hash key casing methods work on arrays

---

lib/puppet/feature/pwshlib.rb

This is a hotfix to resolve an issue customers are seeing after the `v.3.0.0` release of the `puppetlabs-powershell` module. Adding a pwshlib feature will ensure that the powershell provider is only loaded if the functionality is detected. On Linux systems, this should prevent Puppet from throwing the following error:
```
Error: Could not autoload puppet/provider/exec/powershell: Could not load the "ruby-pwsh" library; is the dependency module puppetlabs-pwshlib installed in this environment?
Error: Could not autoload puppet/type/exec: Could not autoload puppet/provider/exec/powershell: Could not load the "ruby-pwsh" library; is the dependency module puppetlabs-pwshlib installed in this environment?
Error: Could not run: Could not autoload puppet/type/exec: Could not autoload …
```

(MODULES-10389) Only load pwshlib if functionality present

---

Rakefile

Previously the rake build task for the gem included logic
for deleting puppet specific code; this is an erroneous
holdover from an earlier implementation.

(MAINT) Remove erroneous deletion from build task

---

metadata.json

Prior to this commit the metadata erroneously claimed support for 4x versions of Puppet, on which it has not been tested and would fail to run due to the safe navigation feature introduced in Ruby 2.3.

Correct supported Puppet lower bound to 5.5.0

---

lib/pwsh.rb

Ensure ruby versions older than 2.3 function correctly

---

.rubocop.yml
Gemfile
lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_functions.ps1
lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_postscript.ps1
lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_preamble.ps1
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this commit the code for the base provider of the new
puppetized DSC modules was vendored into each module; this
meant that if the provider ever needs to be updated, *every*
prior release of the puppetized module would need to be built
again and pushed with an incremented number.
Moving the base provider to the pwshlib Puppet module (which
is this ruby library packaged as a Puppet module) means that
the provider can be updated separately from the PowerShell
builder code and does not require rebuilding puppetized modules,
only updating the reference pin for pwshlib.
This also makes testing the provider easier as it lives in a
ruby library now instead of in a PowerShell module.

(IAC-1045) Add the DSC base Puppet provider to pwshlib

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit the dsc_base_provider used the LOAD_PATH
to find the appropriate Puppet module and retrieve the DSC
resources from it; this does not work in a puppet agent run,
because the resources are placed flatly on disc in lib/puppet
and lib/puppet_x, not per-module as with a puppet apply run.
This commit adds a handler to fall back on relative paths for
discovery in the case where the module cannot be found in the
LOAD_PATH.

(MAINT) Ensure dsc provider finds dsc resources during agent run

---

appveyor.yml
lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/pwsh.rb
lib/pwsh/util.rb
spec/unit/pwsh_spec.rb

Prior to this commit the DSC base provider would occasionally need to send an empty array as a defined property to `Invoke-DscResource`. However, the CIM instance on the other end may not be able to appropriately cast from an empty array to, say a `[String[]]` type; this would cause the run to fail. Furthermore, the provider did not have a way to distinguish between an *absent* setting and an *empty* one. Ruby does not treat empty arrays and nil as the same, even though PowerShell can/does.
This commit adds a special handler for munging the data returned from a get invocation, ensuring that if a property's value is nil AND the property was used for the query AND the resource expects an array, THEN it will set the result to the manifest value or an empty array.
It also strongly types any …

(GH-55) Handle intentionally empty arrays

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_functions.ps1

Prior to this commit the dsc_base_provider could not handle DateTime objects from Puppet, having no useful way to format them for PowerShell nor read them back from a Get result.
This commit adds some minor handling to ensure that any datetimes are cast appropriately in the param hash and can be parsed by Puppet if returned.
- Fixes #57

(GH-57) Handle datetimes in dsc

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit the DSC Base provider inherited from the Resource APIs Simple Provider. This brought with it a limitation in the type definition, requiring all of the generated DSC types to have the ensure attribute. This led to the confusion in puppetlabs/Puppet.Dsc#72 as well as necessitated the filing of puppetlabs/Puppet.Dsc#74 to improve the UX.
This commit removes the dependence on the Simple Provider and instead copies over the code from it - namely, the set method - and modifies it slightly for brevity.
This change sets up a few things:
1. The collapse of the ensure and dsc_ensure attributes. Once merged, the ensure attribute becomes redundant; the provider no longer needs to care about it and it can be removed from both generation and the provider.
2. The dropping of the …

(GH-59) Refactor away from Simple Provider

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/pwsh.rb

This PR removes the special handling for the ensure keyword
from the dsc base provider to facillitate the collapse of the
ensure and dsc_ensure keywords.
- Relates to puppetlabs/Puppet.Dsc#74

(GH-74) Remove special handling for ensure in the dsc base provider

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

This PR removes parameters from the return hash in invoke_get_method of the dsc base provider and also removes the redundant handling for the PSDSCRunAsCredential property, which is always a parameter.
- Related to puppetlabs/Puppet.Dsc#81

(GH-81) Handle parameters in the dsc base provider

---

CHANGELOG.md
lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/pwsh/version.rb
metadata.json

Prior to this commit the dsc base provider erroneously only tried to compare ensurable states on resources which are NOT ensurable instead of only comparing them on resources which ARE ensurable.
This commit corrects that error and adds special handling in `invoke_get_method` for trimming empty properties when returning the representation of an absent resource on the system in order to prevent flapping during Puppet runs.
This should be rebased and merged after #68 and a `0.6.1` release immediately prepped and cut.

(Maint) Fix ensurability in the dsc base provider

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Parameters are never returned from the get method,
which prevented them from being included in the
canonicalized resource hash passed to the set method.
This commit re-adds them to the canonicalized hash.

(MAINT) Ensure parameters are canonicalized

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit, the dsc_ensure keyword would sometimes be
stripped from the Get results by the Resource API when the resource
is absent; this commit ensures that when this happens, it defaults
to Absent for is_ensure to enable appropriate resource creation.

(MAINT) Add handling for when dsc_ensure is stripped

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

This change is required for #https://github.com/puppetlabs/Puppet.Dsc/pull/115
Currently `vendored_modules_path` is set to `puppet_x/dsc_resources` by adding this change the `vendored_modules_path` will be set to `puppet_x/<modulename>/dsc_resources`. 
This provides the capability to install PowerShell module dependencies side by side. 
This PR handlles the old method, eg `puppet_x/dsc_resources`, the new method, eg `puppet_x/<modulename>/dsc_resources` and also the case that something else happens and the `vendored_modules_path` is not set. 
Note: This PR needs to be merged before #https://github.com/puppetlabs/Puppet.Dsc/pull/115

(GH-75) Including module name in vendored module path

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit the `root_module_path` in the `should_to_resource` method of the `dsc_base_provider` downcased the PowerShell module name; this would fail to discover the resources for modules like `7Zip` and `xHyper-V` which are Puppetized as `a7zip` and `xhyper_v` respectively.
This commit uses the `puppetize_name` method to ensure the PowerShell module name is appropriately munged.

Make root module path use puppetized module name

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

These commits prevent duplicate instantiation of Credentials and move the logic for variable instantiation to after the values are first used in a declaration.

(MAINT) Minor fixes to CIM instance handling

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit the comparison in the DSC base provider for values on the node vs values in the manifest was a simple equals check; this works for non-enumerables and for enumerables *so long as* the enumerables are in the same order.
This commit corrects the check to sort the enumerables so that the comparison is done purely on the values, not the order, as PowerShell does not care about the order of items in a hash or array.

(MAINT) Correctly canonicalize enumerable values in dsc

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit the dsc_base_provider checked for the legacy vendored DSC module path before the new, specific path; in cases where the modules installed are a mix of old and new path, the old path will _always_ exist, even if the specific module is not there (because it is looking for the *container*, as the container can hold any number of vendored modules).
This commit inverts the search order, seeking the most specific location *first* and falling back to the general location if needed.

(MAINT) Ensure vendored path check works with mix of module builds

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this PR calling initialize for the dsc base provider would always set the class variables for cached_canonicalized_resource, cached_query_results, and logon_failures to empty arrays; when running with 2 or more resources of a different type, this would cause the provider to reset these values to the empty arrays, thus wiping out these caches, especially the cache for canonicalized resources, which is filled *before* the rest of the Puppet run.
This commit updates the initialize method to instead memoize those caches, only setting them to empty arrays if they do not already exist. This way, canonicalized resources from multiple types are not mysteriously removed from the cache.
- Resolves #97

(GH-97) Memoize class variables in initialize

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit the safety check in the canonicalize method intended to prevent multiple executions to canonicalize the same resource compared the cached resources to the *full* resource being checked; this commit changes that check to only search for a hash containing the matching namevars.
This should prevent multiple runs and bugs where mandatory parameters are dropped during an RSAPI refresh event.

(GH-105) Ensure canonicalized_cache check validates against namevar

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit if a resource is ensurable but the value of `ensure` on the target node was not `Present` or `Absent` the call to run `Invoke-DscResource` never gets made.
This commit updates the logic in the `set` method to call `update()` if the state of the ensurable resource is ambiguous from a CRUD perspective, which is preferable to not running set at all.

(GH-105) Ensure set runs on ambiguous ensure states

---

lib/pwsh.rb

This PR adds in additional search paths for PowerShell 7 which are needed when trying to use the exec resource and having the provider set to pwsh.

feat: adding in paths for PowerShell 7 install

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR the `canonicalize` method in the DSC Base Provider did some unneccessary work:
- it _always_ called `invoke_get_method` if a resource was not already in the canonicalized cache
- it erroneously canonicalized a resource which **should** exist to values which were returned as `nil` from `invoke_get_method` because DSC returns the ensure value as `absent` and `nil` for other properties
This commit adds logic shortcuts to obviate unneccessary canonicalization of the resource when the should value for `dsc_ensure` is `absent` (because a resource being deleted does not care about casing) as well as when the should value for `dsc_ensure` is `present` but the resource itself does not actually exist on the system (a resource which is being created should treat it's own definition …

(GH-125) Fix dsc provider canonicalization for absent resources

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR, some enums would be incorrectly canonicalized to the value returned from `invoke_get_method`; while this is fine for _most_ strings, enums are case sensitive and validated in Puppet. For example, when the result of `invoke_get_method` returns a value of `DWord` for an enum of `Dword`, an error was raised when attempting to canonicalize to the incorrect casing of `DWord`.
This PR:
1. Adds a new `enum_attributes` method which, like the `namevar_attributes` and `parameter_attributes` methods, filters the type attributes to return the list of attribute names (as keys); in this case, for any attribute whose data type includes an Enum.
2. Ensures that enums are not erroneously cased to match system state.
3. Includes new unit tests for the `canonicalize` behavior as well as …

(GH-127) Canonicalize enums correctly

---

lib/pwsh.rb
lib/templates/init.ps1

Prior to this PR, the C# code which is used for the custom PowerShell host referenced Puppet; this is a holdover from when the code was included in the PuppetLabs PowerShell module and was explicitly Puppet-only. Now that the code is vendor-agnostic, the references have been cleaned up to refer to the parent project, ruby-pwsh, instead.
Similarly, other unneccessary Puppet specific references in the init script and PowerShell Manager code have also been removed.

(GH-136) Rename C# namespace to RubyPwsh & remove erroneous Puppet references

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR, a typo in the case statement of the `same?` method in the DSC Base Provider caused the Hash and Array cases never to run, always falling back on a simple `==` value comparison.
This caused arrays which were the same except for ordering to always fail, as `==` comparisons of arrays are order sensitive.
This PR corrects the typo, ensuring that the Array case runs. This only handles order insensitivity of arrays which have no nested values.
A future PR will be required to deeply sort arrays and hashes - see #144 for further details.
This PR also comments out the Hash case, which otherwise errors. This preserves existing behavior for Hashes, causing them to be compared with `==`, which is order insensitive for _keys_ but not for array values (this also will be resolved when …

(GH-143) Handle order insensitive arrays in the `same?` method of the DSC Base Provider

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this commit, the DSC base provider only properly handled secrets when passed as part of a credential and always assumed that the sensitive data was the last string value in a hash.
This commit reworks the handling of sensitive data by:
1. Not munging the formatted PowerShell string to move the `#PuppetSensitive` secret identifier to the outside of a hash.
2. Reworking redaction to work *within* a string instead of only for the last string in a hash declaration.
As a result, a new method was required for removing the sensitive string identifier prior to passing the script string to PowerShell for invocation (lest a password erroneously get `#PuppetSensitive` appended to it). This is done via the new `remove_secret_identifiers` method, which must be called immediately prior to …

(GH-145) Improve DSC secrets redaction

---

.travis.yml
lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this commit value comparisons in the DSC Base Provider only partially worked for arrays and hashes; in PowerShell, the order of a hash or array does not matter for comparison but in Ruby hashes and arrays are order-sensitive.
The `same?` method was meant to get around this but only worked for non-enumerable values and values which were simple arrays.
This commit adds a new `recursively_sort` method to obviate this issue and calls it in `same?`
- Resolves #144

(GH-144) Enable order-insensitive comparisons for DSC

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

This commit cleans up and simplifies the logic in the DSC Base Provider; prior to this commit, the `set` method included handling for `nil` `is` and `should` states in the change hash; with the current implementation, neither of these values can ever be `nil` without reaching a runtime error prior to this method being called.
This commit therefore removes the complexity for handling cases where `is` or `should` are `nil` and removes the never-called method `create_absent` as it is not needed.
This commit further simplifies the `set` method by removing custom handling for retrieving the name hash as the names for Puppetized DSC Resources are always hashes and any extraneous values are stripped in `invoke_set_method` itself.
Resolves #141

(GH-141) Simplify set logic in DSC Base Provider

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this commit, the new handling for secrets was not utilized when preparing credentials for PowerShell. Further, the initial implementation introduced a severe performance hit when attempting to use `gsub` against a 150+ line block of text.
This commit ensures that credential secrets are handled like all other secrets. It also refactors the `redact_secrets` & `remove_secret_identifiers` methods to use a helper method, `handle_secrets`.
This new `handle_secrets` method takes an input string, replacement string, and error message as parameters. It parses the input string, first looking to see if any secrets are in it. If not, it returns the input string. Next, it breaks the input string into separate lines - the original `gsub` regex was causing noticeable performance impacts when …

(MAINT) Refactor secrets handling in DSC

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this commit the call to `canonicalize` for a retrieved resource would return the previously cached canonical value for the specified name hash; in other words, it would return the canonicalized *should* value. The strict check for retrieved data from `get` validates that
calling `canonicalize` does *not* change the result, as it is meant to munge the manifest input into a state that matches what `get` will return.
We have been (ab?)using this functionality to force the manifest values to be case insensitive but case preserving. We do *not* want to munge the return data from the `get` method.
This commit modifies the logic for handling canonicalizing a resource hash to only munge if no entry for the namehash was found in the cache; otherwise, it returns the data as-is.
This can …

(GH-154) Fix canonicalization in `get` method for DSC Base Provider

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR, CIM Instances were not properly munged in `invoke_get_method`. The keys for CIM Instance hashes were camelCased instead of downcased and top-level CIM Instance hashes included the `cim_instance_type` key when only nested CIM Instances should include that key.
This PR ensures that enumerables returned from DSC are appropriately munged by downcasing all hash keys and removing the `cim_instance_type` key from any non-nested CIM Instance properties.
It replaces the `camelcase_hash_keys!` method with the `downcase_hash_keys!` method and introduces the new `munge_cim_instances!` method.
- Closes #155

(GH-155) Fix CIM Instance munging in `invoke_get_method` for DSC Base Provider

---

lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_functions.ps1

Prior to this PR, the `ConvertTo-CanonicalResource` function used to munge the values `Invoke-DscResource` emits for the `Get` method into a usable hash for Puppet/Ruby to consume had minor bugs which:
1. Caused canonicalization of values for empty strings to fail against enums (because Puppet treats an empty string as an invalid enum specification whereas it treats `nil` as `undef`)
2. Caused canonicalization of values for CIM Instances which should be arrays to fail against single-item arrays (because the logic in `ConvertTo-CanonicalResult` mishandled turning single hashes into an array of hashes with a single item).
This PR corrects both issues.

(GH-154) Fix return data from `Invoke-DscResource` for empty strings and single item arrays in DSC Base Provider

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR, the values returned from DSC via `invoke_get_method` were left in the order returned by PowerShell. This caused issues during comparisons during canonicalization due to the Ruby (and therefore Puppet) caring about the ordering of arrays and hashes and PowerShell not.
This PR therefore recursively sorts the result before handing it back, ensuring that canonicalized manifest values and values returned from get are both sorted appropriately, ending the errors and mismatches.
- Resolves #154

(GH-154) Ensure values returned from `invoke_get_method` are recursively sorted in the DSC Base Provider to reduce canonicalization warnings.

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

`should_to_resource` renamed too `invocable_resource` in order to better represent what the method does at a glance and help to ease the understanding of the module.
Logic shared between `invoke_get_method` and `invoke_set_method` has been moved into a new method, `invoke_dsc_resource`. Said logic has in turn been hardened so that it now throws an error and returns nill should any of the following occur:
- if the logon has previously failed
- if nothing is returned from the execution
- if the json cannot be parsed

(GH-147) Refactor Invocation methods to use shared helper and write error logs when appropriate

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this commit an empty error string is treated as a failure. This commit modifies the behavior to not write an error message if the return from DSC was nil or an empty string.
This is a maintenance fix because the buggy code has not been released.

(MAINT) Ensure DSC does not write accidental errors

---

.github/workflows/ci.yml
.gitignore
Gemfile
Rakefile
spec/acceptance/dsc/basic.rb

Prior to this PR, the DSC Base Provider only had unit tests to help validate its functionality.
This commit adds a new acceptance test paradigm which leverages the published `dsc-powershellget` module from the Forge to validate these minimal scenarios:
1. That a resource can be idempotently updated
2. That a resource can be idempotently created
3. That a resource can be idempotently deleted
4. That a `PSDscRunAsCredential` can be specified and used without leaking any secrets into the debug logs
5. That an invalid `PSDscRunAsCredential` errors as expected without leaking any secrets into the debug logs
This PRadds two new rake tasks:
1. `dsc:acceptance:spec_prep`, which creates the modules folder in the spec fixtures if it does not already exist, symlinks the project to that folder as …

(GH-163) Add basic DSC acceptance tests

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Fix has been put in place so that if the returned DateTime is nil it is not parsed and is instead returned as is.
In addition, if the parse ever fails the error is caught and outputted into the context, with nil being returned.

(IAC-1657) Fix for invalid DateTime value error in `invoke_get_method`

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR the DSC base provider had no way to handle resource level insync checks and could only rely on the default property-by-property insync checks in Puppet::Property. This fell short in cases where such a check could not work, such as in cases where the DSC Resource does not return the expected values in Get or had a mismatch between its API spec and the implementation.
This PR:
1. Adds a new class variable, `@@cached_test_results`
2. Adds a new accessor method, `cached_test_results`, to retrieve the cache
3. Adds a new `insync?` method which can be called by the resource API; for more info, see puppetlabs/puppet-resource_api#225. This method only handles custom insync validation for a resource which has the `validation_mode` specified as `resource` and otherwise defaults to …

(GH-145) Add insync? and invoke_test_method to dsc provider

---

Rakefile
lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_postscript.ps1
spec/acceptance/dsc/class.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR, it was not possible to use the DSC Base Provider to invoke class-based DSC Resources. DSC `1.1` (the version of DSC used by Windows PowerShell `5.1`) cannot call `Invoke-DscResource` for class- based resources by module path, only by module name; further more, the module containing the DSC Resource _must_ be available in the *system* level `PSModulePath` environment variable; munging the *process* level `PSModulePath` does not work.
This PR updates the DSC Base Provider to:
1. Read the `dscmeta_resource_implementation` value from a the Puppet Resource API type definition of a resource and inject it into the invocable resource definition
2. Add the `munge_psmodulepath` method to return the PowerShell code to modify the system-level `PSModulePath` if the invocable resource …

(GH-172) Enable use of class-based DSC Resources by munging PSModulePath 

---

.gitignore
Rakefile
spec/acceptance/dsc/complex.rb

This PR adds acceptance tests for the DSC Base Provider which:
1. Validates the interoperation of Puppet resources and DSC resources
2. Validates the use of the same DSC Resource type to manage two
resources simultaneously
3. Validates the use of different DSC Resources in the same Puppet run
4. Validates the use of DSC Resources with metaparameters
- resolves #164

(GH-164) Add complex DSC acceptance tests

---

Rakefile
lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_functions.ps1
spec/acceptance/dsc/cim_instances.rb

This PR adds acceptance testing to validate the behavior of nested CIM instances for Puppetized DSC Resources. In the process of writing this acceptance testing, a bug was discovered that prevented the canonicalization of DSC Resource data where a nested cim instance has a value of `$null` and Puppet expects an array.
This PR corrects that error and implements acceptance testing validating it.
Resolves #165

(GH-165) Ensure null-value nested cim instance arrays are appropriately munged

---

lib/pwsh.rb
spec/unit/pwsh_spec.rb

Prior to this commit, the instance_key method for the PowerShell Manager only partially
respected the uniqueness of a possible instance; if there are any differences between
two declarations in the path to the executable, arguments passed to the executable, or
the debug option, the manager would treat the new instance as expected, spinning up an
additional instance of the manager.
However, it completely ignored the pipe_timeout option, meaning specifying an instance
with a default pipe_timeout and a second instance with a pipe_timeout of 45 would
**actually** result in the second instance declaration just reusing the existing instance
with the default timeout, which is unwanted an unexpected behavior.
This commit modifies the logic for the instance_key method slightly by making the key a …

(GH-180) Ensure instance_key respects full uniqueness of options

---

lib/templates/init.ps1

When Protected Event Logging and PowerShell Script Block logging are enabled together the SystemRoot environment variable is a requirement.
If it is removed as part of the environment purge it causes the PowerShell process to crash, therefore breaking the pipe between Ruby and the remote PowerShell session.
This PR fixes the issue by creating a filtered list of environment variables which does not include the SystemRoot environment variable.
This list can then be purged safely.
Closes #188

(GH-188) Filter current environment variables

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Prior to this PR metaparameters were not preserved during the initial canonicalization of a resource.
This PR ensures that canonicalization preserves any metaparameters that may be present in a given resource.

(MODULES-11343) Preserve metaparameters

---

.github/workflows/ci.yml
.github/workflows/labeller.yml
.github/workflows/release.yml
.github/workflows/release_prep.yml
Rakefile
ruby-pwsh.gemspec
spec/unit/pwsh_spec.rb

This PR includes a number of fixes and improvements for the workflows in this project.

(MAINT) CI Updates

---

.github/workflows/release.yml

Prior to this commit the release workflow had three sub jobs.
This is not required so this commit consolidates all steps in to a single job.

(MAINT) Simplify release

---

.github/workflows/ci.yml
.github/workflows/custom_acceptance.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/release_prep.yml
.rubocop_todo.yml
metadata.json

This PR Adds support for Puppet 8.
It also drops support for Puppet 6.
Most work already completed in https://github.com/puppetlabs/ruby-pwsh/pull/208

(CAT-1172) - Add Puppet 8 Support/Drop Puppet 6 Support

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

This is a continuation of https://github.com/puppetlabs/ruby-pwsh/pull/204 by https://github.com/Hvid & https://github.com/ShawnHardwick.
Fixes https://github.com/puppetlabs/ruby-pwsh/issues/203 and https://github.com/puppetlabs/Puppet.Dsc/issues/242
This is just copied from the comment by https://github.com/ShawnHardwick
We can say with confidence that this change **should not** break existing DSC functionality thanks to tests added from these issues:
https://github.com/puppetlabs/ruby-pwsh/issues/163
https://github.com/puppetlabs/ruby-pwsh/issues/164
https://github.com/puppetlabs/ruby-pwsh/issues/165
These tests thoroughly test changes to the dsc base provider against published dsc modules.

(bug) - Fixes missing mandatory ID

---

README.md

(maint) - Update readme

---

.github/workflows/release_prep.yml

Prevents module release-prep force pushing release prep pr already present and overwriting the changes.

(maint) - update release prep

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Prior to this PR, the vendored dsc module would only be loading into the PSModulePath Env variable if the dsc resource type was implemented as a Class.
Now that DSC Modules seem to be taking the approach of abstracting the DscResource.Base into a seperate module which is then imported, we need to alter the PSModulePath Env variable to include the vendored modules path to ensure this module and its classes (Resource Base) are imported as expected.
Its worth noting that ruby-pwsh will only temporarily add the vendored module path to the PSModulePath Env variable during the puppet agent run, before removing it again in the Dsc resource post invocation script.
Fixes https://github.com/puppetlabs/ruby-pwsh/issues/262

(CAT-1617) - Always load vendored module in PSModulePath

---

Rakefile
lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Tests were removed by mistake during CONT-867, so subsequent test breakage at 3a9156a9af16a6ad3ff9a2bfa179adb18f4b9d28 was easily missed.
This reimplements the missing test cases to the spec rake task, and fixes the broken tests.

(maint) - Run all unit test files during rake spec

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Linked to issue : https://github.com/puppetlabs/ruby-pwsh/issues/265
Fixes the fact that enum are not idempotent
https://github.com/puppetlabs/ruby-pwsh/issues/265

Fix enum idempotency

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

General cleanup and refactor of the `retry_invoke_dsc_resource` method.
Functionality remains largely unchanged, except for removal of a redundant notice.

(maint) - refactor retry_invoke_dsc_resource

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

```
Warning: Provider returned data that does not match the Type Schema for `dsc_smbshare[Integrations]`
Value type mismatch:
* dsc_path:  (expects a String value, got Undef)
```
Prior to this PR, we would see the above error returned when dsc would return a nil value for a required string in its data hash.
As puppet is not expecting a nil value, but rather a complete or empty string, the error is raised on each puppet run where this occurs.
We can fix this by converting all required string attributes values returned in the data hash by DSC from nil to an empty string ('').

(CAT-1724) - Fix Provider returned data not matching Type Schema

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/pwsh.rb
lib/pwsh/util.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Adds cross-platform unit testing support for resources implemented by the `dsc_base_provider`.
1. Allow dsc_base_provider.ps_manager to use `pwsh` on non-Windows.
2. Hardcode path delimiter to ':' for splitting Unix $PATH system variable to determine pwsh_path.
3. Update Pwsh::Utils.on_windows? to reliable identify the OS running the Ruby interpreter to correctly identify if pwsh or Powershell should be used for dsc_base_provider.canonicalize. 
4. Update dsc_base_provider spec tests to validate .ps_manager using pwsh_path and pwsh_args for non-Windows usage  
1. The provider `dsc_base_provider` is hardcoded to use Windows PowerShell paths instead of the platform agnostic `pwsh` which forces unit testing on non-Windows OS to fail waiting for a PowerShell process to respond. 
``` shell
> …
```

Add support for unit testing via Unix OS

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

This PR introduces a new instance variable @timeout, set
to nil by default. A new method set_dsc_timeout is added to
handle the setting of @timeout based on the name_hash[:dsc_timeout]
value. This timeout specifies the number of seconds the ps_manager will
await the dsc invocation to return, before moving on.
The ps_manager.execute method call now includes the timeout value.
The error message for when output is nil has been updated to include
information about the timeout, if it is set.
Does not affect previous behaviour, therefore is completely backwards
compatible with previous versions.

(CAT-1869) - Add configurable dsc_timeout

---

README.md

This PR adds a warning the readme about the use of sensitive data with script block logging enabled. As per microsoft's own recommendation, protected event logging should also be enabled to encyrpt this data.

(maint) - add disclaimer for script block logging

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

(bug) - Fix dsc timeout matcher

---

spec/unit/pwsh/util_spec.rb

Fixes a unit test wrongly configured in https://github.com/puppetlabs/ruby-pwsh/pull/334.
The `invalid_directories?` method should return true if passed a path that exists, but is a file. As we did not stub File.exists? the incorrect test went unnoticed.

(maint) - Fix incorrect test for file_path

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Reinstating reverted change by [Clebam](https://github.com/Clebam) with additional fix suggested by original author.
Original PR: https://github.com/puppetlabs/ruby-pwsh/pull/292
Revert PR: https://github.com/puppetlabs/ruby-pwsh/pull/342
Reason for revert: https://github.com/puppetlabs/ruby-pwsh/issues/340
Original author: https://github.com/Clebam

(CAT-2061) Fix empty string nullification

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb

Supersedes https://github.com/puppetlabs/ruby-pwsh/pull/359

(Bug): do not pass dsc_timeout as timeout parameter to DSC resource params

---

lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
lib/puppet/provider/dsc_base_provider/invoke_dsc_resource_postscript.ps1
spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb

Here was the method of set PSPath-Variable changed from [System.Environment]::SetEnvironmentVariable() to Set-ItemProperty. This brings a performance advantage, because the function can have [System.Environment]::SetEnvironmentVariable() timeouts ([see also](https://stackoverflow.com/questions/4825967/environment-setenvironmentvariable-takes-a-long-time-to-set-a-variable-at-user-o)).
https://github.com/puppetlabs/ruby-pwsh/issues/363

Change [System.Environment]::SetEnvironmentVariable() to Set-ItemProperty
