puppetlabs/ruby-pwsh

- lib/pwsh.rb
Add a method to return the hash of instances, fix a small typo.
> (MAINT) Add instances method

- CHANGELOG.md
- lib/pwsh/util.rb
- lib/pwsh/version.rb
- metadata.json
Deployed to [RubyGems](https://rubygems.org/gems/ruby-pwsh/versions/0.2.0) and to the [Puppet Forge](https://forge.puppet.com/puppetlabs/pwshlib)
> Mergeback 0.2.0 Release

- README.md
Minor update to readme release instructions.
> (maint) Minor README change

- lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Sorry, my original pull request missed this very important bit.
> (MAINT) Place nil check when assigning is_same

- lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Implements different sorting of Hash and Array values.
> (Maint) Ensure canonicalize correctly compares sorted hashes

- spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
This should be merged after #129
- resolves #126
> (GH-126) Add tests for canonicalization of nil values

- lib/templates/init.ps1
Paired on this with James Pogran to figure out what most of the invocation-specific code is doing - this PR does not take care to thoroughly document the commands and behavior around the Pipe Server or the C# code but does annotate the behavior most likely to be modified for functionality.
When this script is broken up into component pieces, the individual functions should get full comment-based help and the extracted C# code should get full reference docs.
> (GH-137) Add explanatory comments to init.ps1

- lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
- spec/unit/puppet/provider/dsc_base_provider/dsc_base_provider_spec.rb
> (GH-73) Add unit tests to DSC Base Provider

- CHANGELOG.md
- lib/pwsh/version.rb
- metadata.json
This PR prepares ruby-pwsh for the release of v0.10.3
> Release prep

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/labeller.yml
- .github/workflows/publish.yml
- Gemfile
- README.md
This PR contains the following workflow improvements:
- Adds a dependabot schedule
- Adds a publish workflow
- Refactors the existing CI workflow
> (MAINT) Workflow improvements

- metadata.json
> (maint) - Drop Support for Windows 2008(R2)/7/8

- metadata.json
> (maint) - Drop Support for OSX 10.14

- metadata.json
> (maint) - Drop Support for Fedora 30&31

- metadata.json
> (maint) - Drop Support for Debian 8/9

- metadata.json
> (feat) - Add support for Debian 11

- metadata.json
> (feat) - Add support for OSX 11&12

- metadata.json
> (feat) - Add support for Fedora 36

- .github/workflows/release_prep.yml
> Maint update release prep

- .github/workflows/mend.yml
> (maint) - Update mend trigger

- .github/workflows/mend.yml
> (test) - update workflow ref to test changes

- .github/workflows/mend.yml
This reverts commit aafa71d5d3e900855ef7fe7969b3ae77f9fa63ab.
> Revert "(test) - update trigger to test changes"

- .pdkignore
- .vscode/extensions.json
- Gemfile
- metadata.json
This commit runs the PDK update command to bring the Gemfile and other configuration up to date with current standards.
> (MAINT) Run PDK update

- metadata.json
Allows for AlmaLinux 8/9 support following issue #329 .
> AlmaLinux 8/9 added to metadata.json

- README.md
Updating readme to include almalinux under supported operating systems
> updated readme for almalinux

- lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb
Ensure metaparams preserves casing
https://github.com/puppetlabs/ruby-pwsh/issues/373
https://github.com/puppetlabs/ruby-pwsh/issues/373
> Ensure metaparams casing is preserved
